export const paintingMaterialFilterOptions = [
	{ label: 'Canvas', value: 'canvas' },
	{ label: 'Paper', value: 'paper' },
	{ label: 'Wood Panel', value: 'wood_panel' },
	{ label: 'Board', value: 'board' },
	{ label: 'Cardboard', value: 'cardboard' },
	{ label: 'Canvas Board', value: 'canvas_board' },
	{ label: 'Canvas Pad', value: 'canvas_pad' },
	{ label: 'Fabric', value: 'fabric' },
	{ label: 'Acrylic Paper', value: 'acrylic_paper' },
	{ label: 'Watercolor Paper', value: 'watercolor_paper' },
	{ label: 'Oil Paper', value: 'oil_paper' },
	{ label: 'Mixed Media Paper', value: 'mixed_media_paper' },
	{ label: 'Pastel Paper', value: 'pastel_paper' },
	{ label: 'Masonite', value: 'masonite' },
	{ label: 'Metal', value: 'metal' },
	{ label: 'Glass', value: 'glass' },
	{ label: 'Ceramic', value: 'ceramic' },
	{ label: 'Plastic', value: 'plastic' },
	{ label: 'Plexiglass', value: 'plexiglass' },
	{ label: 'Wood', value: 'wood' },
	{ label: 'Cardstock', value: 'cardstock' },
	{ label: 'Jute', value: 'jute' },
	{ label: 'Silk', value: 'silk' },
	{ label: 'Vellum', value: 'vellum' },
];

export const sculptureMaterialFilterOptions = [
	{ label: 'Marble', value: 'marble' },
	{ label: 'Bronze', value: 'bronze' },
	{ label: 'Wood', value: 'wood' },
	{ label: 'Stone', value: 'stone' },
	{ label: 'Clay', value: 'clay' },
	{ label: 'Steel', value: 'steel' },
	{ label: 'Aluminum', value: 'aluminum' },
	{ label: 'Plaster', value: 'plaster' },
	{ label: 'Resin', value: 'resin' },
	{ label: 'Copper', value: 'copper' },
	{ label: 'Concrete', value: 'concrete' },
	{ label: 'Glass', value: 'glass' },
	{ label: 'Iron', value: 'iron' },
	{ label: 'Terracotta', value: 'terracotta' },
	{ label: 'Acrylic', value: 'acrylic' },
	{ label: 'Fiberglass', value: 'fiberglass' },
	{ label: 'Mixed Media', value: 'mixed_media' },
	{ label: 'Ceramic', value: 'ceramic' },
	{ label: 'Wood Composite', value: 'wood_composite' },
	{ label: 'Paper Mâché', value: 'paper_mache' },
	{ label: 'Leather', value: 'leather' },
	{ label: 'Textile', value: 'textile' },
	{ label: 'Plastic', value: 'plastic' },
];

export const drawingMaterialFilterOptions = [
	{ label: 'Graphite', value: 'graphite' },
	{ label: 'Charcoal', value: 'charcoal' },
	{ label: 'Colored Pencils', value: 'colored_pencils' },
	{ label: 'Ink', value: 'ink' },
	{ label: 'Pen', value: 'pen' },
	{ label: 'Pastels', value: 'pastels' },
	{ label: 'Markers', value: 'markers' },
	{ label: 'Watercolor Pencils', value: 'watercolor_pencils' },
	{ label: 'Oil Pastels', value: 'oil_pastels' },
	{ label: 'Crayons', value: 'crayons' },
	{ label: 'Chalk', value: 'chalk' },
	{ label: 'Digital Tablet', value: 'digital_tablet' },
	{ label: 'Drawing Paper', value: 'drawing_paper' },
	{ label: 'Watercolor Paper', value: 'watercolor_paper' },
	{ label: 'Sketchbook', value: 'sketchbook' },
	{ label: 'Canvas', value: 'canvas' },
	{ label: 'Vellum', value: 'vellum' },
	{ label: 'Bristol Board', value: 'bristol_board' },
	{ label: 'Cardstock', value: 'cardstock' },
	{ label: 'Mixed Media Paper', value: 'mixed_media_paper' },
	{ label: 'Textured Paper', value: 'textured_paper' },
	{ label: 'Graph Paper', value: 'graph_paper' },
];

export const digitalArtMaterialFilterOptions = [
	{ label: 'Digital Tablet', value: 'digital_tablet' },
	{ label: 'Stylus Pen', value: 'stylus_pen' },
	{ label: 'Graphic Software', value: 'graphic_software' },
	{ label: '3D Modeling Software', value: '3d_modeling_software' },
	{ label: 'Photo Editing Software', value: 'photo_editing_software' },
	{ label: 'Vector Graphics Software', value: 'vector_graphics_software' },
	{ label: 'Digital Brushes', value: 'digital_brushes' },
	{ label: 'Digital Paints', value: 'digital_paints' },
	{ label: 'Layer Masks', value: 'layer_masks' },
	{ label: 'Texture Packs', value: 'texture_packs' },
	{ label: 'Color Palettes', value: 'color_palettes' },
	{ label: '3D Models', value: '3d_models' },
	{ label: 'Vector Graphics', value: 'vector_graphics' },
	{ label: 'Digital Collage Tools', value: 'digital_collage_tools' },
	{ label: 'Motion Graphics Software', value: 'motion_graphics_software' },
	{ label: 'Augmented Reality Tools', value: 'augmented_reality_tools' },
	{ label: 'Virtual Reality Tools', value: 'virtual_reality_tools' },
	{ label: 'Animation Software', value: 'animation_software' },
	{ label: 'Interactive Design Tools', value: 'interactive_design_tools' },
	{ label: 'Digital Canvas', value: 'digital_canvas' },
	{ label: 'Pixel Art Tools', value: 'pixel_art_tools' },
	{ label: 'Photo Manipulation Tools', value: 'photo_manipulation_tools' },
	{ label: 'Digital Sculpting Software', value: 'digital_sculpting_software' },
];

export const handmadeArtMaterialFilterOptions = [
	{ label: 'Watercolor Paint', value: 'watercolor_paint' },
	{ label: 'Oil Paint', value: 'oil_paint' },
	{ label: 'Acrylic Paint', value: 'acrylic_paint' },
	{ label: 'Charcoal', value: 'charcoal' },
	{ label: 'Graphite', value: 'graphite' },
	{ label: 'Pastels', value: 'pastels' },
	{ label: 'Ink', value: 'ink' },
	{ label: 'Pen', value: 'pen' },
	{ label: 'Colored Pencils', value: 'colored_pencils' },
	{ label: 'Clay', value: 'clay' },
	{ label: 'Wood', value: 'wood' },
	{ label: 'Metal', value: 'metal' },
	{ label: 'Fabric', value: 'fabric' },
	{ label: 'Leather', value: 'leather' },
	{ label: 'Textile', value: 'textile' },
	{ label: 'Beads', value: 'beads' },
	{ label: 'Wire', value: 'wire' },
	{ label: 'Glass', value: 'glass' },
	{ label: 'Ceramic', value: 'ceramic' },
	{ label: 'Paper', value: 'paper' },
	{ label: 'Cardstock', value: 'cardstock' },
	{ label: 'Canvas', value: 'canvas' },
	{ label: 'Wood Panel', value: 'wood_panel' },
	{ label: 'Mosaic Tiles', value: 'mosaic_tiles' },
	{ label: 'Plaster', value: 'plaster' },
	{ label: 'Stone', value: 'stone' },
	{ label: 'Epoxy Resin', value: 'epoxy_resin' },
	{ label: 'Jute', value: 'jute' },
	{ label: 'Origami Paper', value: 'origami_paper' },
];
