export const stylePaintingOptions = [
	{ label: 'Abstract', value: 'abstract' },
	{ label: 'Impressionism', value: 'impressionism' },
	{ label: 'Realism', value: 'realism' },
	{ label: 'Expressionism', value: 'expressionism' },
	{ label: 'Surrealism', value: 'surrealism' },
	{ label: 'Cubism', value: 'cubism' },
	{ label: 'Modernism', value: 'modernism' },
	{ label: 'Contemporary', value: 'contemporary' },
	{ label: 'Pop Art', value: 'popArt' },
	{ label: 'Minimalism', value: 'minimalism' },
	{ label: 'Renaissance', value: 'renaissance' },
	{ label: 'Baroque', value: 'baroque' },
	{ label: 'Art Nouveau', value: 'artNouveau' },
	{ label: 'Naïve Art', value: 'naïveArt' },
	{ label: 'Folk Art', value: 'folkArt' },
	{ label: 'Photorealism', value: 'photorealism' },
	{ label: 'Street Art/Graffiti', value: 'streetArt/Graffiti' },
	{ label: 'Fantasy', value: 'fantasy' },
	{ label: 'Figurative', value: 'figurative' },
];

export const styleSculptureOptions = [
	{ label: 'Abstract', value: 'abstract' },
	{ label: 'Classical', value: 'classical' },
	{ label: 'Realism', value: 'renaissance' },
	{ label: 'Expressionism', value: 'expressionism' },
	{ label: 'Baroque', value: 'baroque' },
	{ label: 'Neoclassical', value: 'neoclassical' },
	{ label: 'Modernism', value: 'modernism' },
	{ label: 'Minimalism', value: 'minimalism' },
	{ label: 'Surrealism', value: 'surrealism' },
	{ label: 'Cubism', value: 'cubism' },
	{ label: 'Romanticism', value: 'romanticism' },
	{ label: 'Constructivism', value: 'constructivism' },
	{ label: 'Pop Art', value: 'popArt' },
	{ label: 'Kinetic', value: 'kinetic' },
	{ label: 'Conceptual', value: 'conceptual' },
	{ label: 'Art Nouveau', value: 'artNouveau' },
	{ label: 'Art Deco', value: 'artDeco' },
	{ label: 'Primitive/Tribal', value: 'primitive/Tribal' },
	{ label: 'Environmental/Earth Art', value: 'environmental/Earth Art' },
	{ label: 'Street Art', value: 'streetArt' },
	{ label: 'Renaissance', value: 'renaissance' },
	{ label: 'Folk Art', value: 'folkArt' },
	{ label: 'Fantasy', value: 'fantasy' },
];

export const styleDrawingOptions = [
	{ label: 'Realism', value: 'realism' },
	{ label: 'Impressionism', value: 'impressionism' },
	{ label: 'Expressionism', value: 'expressionism' },
	{ label: 'Abstract', value: 'abstract' },
	{ label: 'Surrealism', value: 'surrealism' },
	{ label: 'Cubism', value: 'cubism' },
	{ label: 'Minimalism', value: 'minimalism' },
	{ label: 'Modernism', value: 'modernism' },
	{ label: 'Conceptual', value: 'conceptual' },
	{ label: 'Illustration', value: 'illustration' },
	{ label: 'Comic/Cartoon', value: 'comic/Cartoon' },
	{ label: 'Fantasy', value: 'fantasy' },
	{ label: 'Anime/Manga', value: 'anime/Manga' },
	{ label: 'Line Art', value: 'lineArt' },
	{ label: 'Sketch', value: 'sketch' },
	{ label: 'Figure Drawing', value: 'figureDrawing' },
	{ label: 'Portraiture', value: 'portraiture' },
	{ label: 'Architectural Drawing', value: 'architecturalDrawing' },
	{ label: 'Nature/Botanical', value: 'nature/Botanical' },
	{ label: 'Street Art', value: 'streetArt' },
	{ label: 'Gothic', value: 'gothic' },
	{ label: 'Art Nouveau', value: 'artNouveau' },
	{ label: 'Art Deco', value: 'artDeco' },
	{ label: 'Folk Art', value: 'folkArt' },
];

export const styleDigitalArtOptions = [
	{ label: '3D Art', value: '3d_art' },
	{ label: 'Digital Painting', value: 'digital_painting' },
	{ label: 'Pixel Art', value: 'pixel_art' },
	{ label: 'Vector Art', value: 'vector_art' },
	{ label: 'Photomanipulation', value: 'photomanipulation' },
	{ label: 'Concept Art', value: 'concept_art' },
	{ label: 'Anime/Cartoon', value: 'anime_cartoon' },
	{ label: 'Fantasy', value: 'fantasy' },
	{ label: 'Sci-Fi', value: 'sci_fi' },
	{ label: 'Cyberpunk', value: 'cyberpunk' },
	{ label: 'Retrowave', value: 'retrowave' },
	{ label: 'Surreal', value: 'surreal' },
	{ label: 'Abstract', value: 'abstract' },
	{ label: 'Illustration', value: 'illustration' },
	{ label: 'Matte Painting', value: 'matte_painting' },
	{ label: 'Typography', value: 'typography' },
	{ label: 'Glitch Art', value: 'glitch_art' },
	{ label: 'Digital Collage', value: 'digital_collage' },
	{ label: 'Portrait', value: 'portrait' },
	{ label: 'Landscape', value: 'landscape' },
	{ label: 'Character Design', value: 'character_design' },
	{ label: 'UI/UX Design', value: 'ui_ux_design' },
	{ label: 'Game Art', value: 'game_art' },
	{ label: 'VFX', value: 'vfx' },
	{ label: 'Motion Graphics', value: 'motion_graphics' },
	{ label: 'VR/AR Art', value: 'vr_ar_art' },
];

export const styleHandmadeFilterOptions = [
    { label: 'Watercolor', value: 'watercolor' },
    { label: 'Oil Painting', value: 'oil_painting' },
    { label: 'Acrylic Painting', value: 'acrylic_painting' },
    { label: 'Pastel', value: 'pastel' },
    { label: 'Charcoal', value: 'charcoal' },
    { label: 'Ink Drawing', value: 'ink_drawing' },
    { label: 'Graphite Drawing', value: 'graphite_drawing' },
    { label: 'Pen and Ink', value: 'pen_and_ink' },
    { label: 'Mixed Media', value: 'mixed_media' },
    { label: 'Collage', value: 'collage' },
    { label: 'Printmaking', value: 'printmaking' },
    { label: 'Ceramics', value: 'ceramics' },
    { label: 'Sculpture', value: 'sculpture' },
    { label: 'Textile Art', value: 'textile_art' },
    { label: 'Embroidery', value: 'embroidery' },
    { label: 'Pottery', value: 'pottery' },
    { label: 'Woodworking', value: 'woodworking' },
    { label: 'Metalwork', value: 'metalwork' },
    { label: 'Jewelry Design', value: 'jewelry_design' },
    { label: 'Handmade Books', value: 'handmade_books' },
    { label: 'Origami', value: 'origami' },
    { label: 'Mosaic', value: 'mosaic' },
    { label: 'Glass Art', value: 'glass_art' },
    { label: 'Leathercraft', value: 'leathercraft' },
    { label: 'Prints', value: 'prints' }
  ];